name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.16-alpine3.20
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 159159
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.20'
       id: go

     - name: checkout code into the Go module directory
       uses: actions/checkout@v4

     - name: Run migration
       run: make migrateup

     - name: Test
       run: make test